name: go-with-ci
on:  
  pull_request:
    branches:
      - develop

jobs:
  check-go-app:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: ['1.18', '1.19']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: runing tests in golang
        run: go test

      - name: run application math
        run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: false # TODO mude para true se quiser fazer o push para o dockerhub
          tags: wesleypraca/go_app:latest

    